### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by SnakeMAR** [usineur/bermuda#1]
Sometime, the game crash, when you pass one screen to another, without any reason.
Saddly, no more details about this... :/

Parfois, le jeu plante, d'un tableau à un autre, sans aucune raison particulière.
Malheureusement, pas plus de détails à propos de ce problème, vu qu'il se manifeste aléatoirement...

**Comment by usineur** [comment]
Ok, faudra que quelqu'un m'explique comment fonctionne les notifications sur github.
Bref, je n'avais pas vu ton message.

Ca vient du moteur d'origine. J'ai constaté le même problème sur la version PC.

Du coup il serait plus pertinent de relayer l'information à l'auteur du moteur. A l'occasion, je prendrai le temps de lui exposer ce problème. La version PC permet d'obtenir plus facilement des logs pour le debug.

**Comment by SnakeMAR** [comment]
Je ne savais pas que la version PC avait ce problème. 

Pour ma part, j'ai constaté un cycle récurant, premièrement c'est la boucle musicale qui plante, ensuite on peut prévoir quelques tableaux à l'avance le plantage dès que la musique est arrêtée.

C'est cyxx qui est responsable de la version PC?

**Comment by usineur** [comment]
Ah, intéressante cette info. Sur la version PC, les crashs que j'ai eu venaient de la gestion des opcodes.
Du coup, faut que je checke. J'ai possiblement des soucis propres à la version Vita.

C'est cyxx qui a reverse le moteur oui. Mais si tu veux lui remonter une anomalie, il faut te baser sur la version PC.

Je vais investiguer de mon côté avant de lui remonter quoi que ce soit. Je dois m'assurer que je n'ai pas introduit de régressions.

**Comment by usineur** [comment]
J'ai commité une modif concernant la partie "son". La mémoire allouée aux musiques n'était pas correctement libérée.

Du coup, la raison pour laquelle le jeu plantait était que la mémoire se retrouvait très vite saturée, ce qui provoquait le crash.

Si tu es en mesure de tester de ton côté, je suis preneur, bien entendu.

**Comment by SnakeMAR** [comment]
Ok!
Je fais le test dans la soirée et je t'en informerai ici même.

Par contre je n'ai pas de quoi le recompiler en vpk.

**Comment by usineur** [comment]
Merci, et le vpk:
https://ferb.fr/vita/tmp/bermuda-vita.vpk

**Comment by SnakeMAR** [comment]
Bon, après plusieurs essais, la majeur partie du problème est résolu. Par contre le problème se manifeste de nouveau après un dialogue entre les différents personnages ; la musique se coupe, puis après quelques tableaux, plantage.

**Comment by usineur** [comment]
Merci pour tes retours,

je pense avoir isolé le problème. J'ai pu jouer hier 20 minutes sans aucun plantage.
Je te mets le vpk à dispo ici: https://ferb.fr/vita/tmp/bermuda-vita-test2.vpk

Si tu peux tester de ton côté... Si tout va bien, je commiterai les modifs.

**Comment by SnakeMAR** [comment]
Je t'en prie.

Il semblerait que le problème soit résolu, j'ai joué pendant presque une heure; quel plaisir !

J'aurais quelques suggestion à te proposer mais cela n'a aucun rapport avec ce "bug" désormais résolu, cependant je n'arrive pas à créer une requête. Je vais tenter de le faire autrement.

Bon travail!

**Comment by usineur** [comment]
Super ! Merci pour tes retours.

Pas de souci, toute suggestion est la bienvenue.

Je ferme donc cette issue, résolue par les commits c6ccada13624847b3382ede5b42f48231044905f et e1c73f9921611fd6d539307bae831101a8fe14e0
