### ISSUE TITLE
Switch: Number "2" permanently displayed on top left screen corner

### ISSUE THREAD

**Issue by rsn8887** [usineur/bermuda#4]
The number "2" is always displayed in the top left corner. Maybe a debugging thing that was left on?

**Comment by usineur** [comment]
Well, I don't have this behavior.
A textinfo is displayed temporarily in this corner only if you press ZR or ZL.

Could you please retry with this [nro](https://www.ferb.fr/switch/bs.nro) ? It also fix issue #5.

**Comment by rsn8887** [comment]
Thanks for the quick response :)

I think maybe I pressed ZR or ZL accidentally during a video sequence, when I tested? Maybe that caused the "2" to stay? For sure, the "2" never went away last night. I will test again with your .nro tonight. Don't have Switch atm.

**Comment by rsn8887** [comment]
The number “2” display seems not reproducible in latest nro you linked.
